articles/post-wsuwp_uc_person.php, parts/single-layout-wsuwp_uc_person.php, single.php, style.css
* Use only featured image, not thumbnail or background image. Background image may be used in the future.
* Single people templates should have a `halves` followed by a `single`.
* Adjust styling to match.
=> [PR] Provide better default views for people

inc/builder.php, inc/builder/core/base.php, inc/builder/core/js/app.js, inc/builder/core/templates/overlay-tinymce.php
A bunch of whitespace changes in this diff to make future merges easier. I gave it too much effort to restyle code before. ;)
=> Merge upstream changes from Make 1.4.8

functions.php, includes/admin.css
=> [PR] Apply styles for the full screen MCE editor to fill a full screen

includes/theme-navigation.php
This enables the default "Overview" behavior.
=> [PR] Correct misspelled filter for BU Navigation

style.css
=> Apply mobile unfloat to larger images only

functions.php, styles/bookmark.css
• Adds attached image awareness to each `<article>` in listings. This is preparatory for being able to use features images on listings/archive pages.
• Refines implementation of "main header" in bookmark style.
=> Image alignment

functions.php
* Deregister the open-sans style enqueued by WordPress core
* Replace core functionality by ensuring a set of default Open Sans
fonts is available to WordPress when the admin bar is showing
* Ensure a set of default Open Sans fonts is available for use by
the Spine when Open Sans is enabled for the theme.
* Add the latin and latin-ext subsets to the font styles
=> [PR] Refactor theme handling of Open Sans font enqueue

spine/footer.php
=> Change to myWSU markup to reflect name change

spine/footer.php
Reverts washingtonstateuniversity/WSUWP-spine-parent-theme#215
We aren't ready to do this name change yet. :disappointed:
=> Revert "Change to myWSU markup to reflect name change"

single.php
=> [PR] Check for empty featured images on individual post layouts as well

includes/theme-images.php, parts/featured-images.php, single.php
Rolls back changes in #222 and #219 in favor of just handling this at the source.
=> [PR] Only return true for spine_has_featured_image if a source exists

spine/footer.php
This should wait for merge until we're ready to make this change in production.
=> [PR] Reintroduce myWSU Naming in Spine

style.css
=> [PR] Apply a default style to `dd` and `dt` elements in Events

functions.php
=> [PR] Enable the builder template by default

includes/theme-images.php, parts/featured-images.php, single.php
This takes advantage of the various classes provided by the WSU
Spine for positioning backgrounds.
=> [PR] Capture position to use when featured image is a background

articles/post.php, functions.php, includes/customizer/customizer.php, style.css
* This will be hidden by default (at first).
* Options are hidden, top, bottom, and both for individual posts only.
=> [PR] Add a social sharing bar for single posts, enabled through the Customizer

functions.php
This is the more recommended option and the one we change the most
frequently when creating sites on the platform.
=> [PR] Set the default Spine grid style to fluid

includes/theme-customizer.php
This is already the default Spine option, but was not reflected
properly in the Customizer interface.
=> [PR] Set the default grid style in Customizer to fluid

builder-templates/css/sections.css, builder-templates/front-end/columns.php, inc/builder.php
=> [PR] Add backgrounds to columns

style.css
Addresses #98, #99, and #101. @jeremyfelt #reviewmerge?
Should be tested on mobile devices and IE.
=> [PR] Page builder banner styling

style.css
Fixes #186, #249 @jeremyfelt #reviewmerge?
=> [PR] Default gallery styles

inc/builder/core/base.php, inc/builder/core/js/views/section.js
Fixes #206 @jeremyfelt #reviewmerge?
=> [PR] Reintroduce confirmation box when deleting a section

inc/builder/core/js/views/section.js
Fixes #204 @jeremyfelt #reviewmerge?
=> [PR] Apply section labels dynamically

functions.php, parts/share-tools.php
Fixes #301 @jeremyfelt #reviewmerge?
=> [PR] Twitter share text

inc/builder.php, js/spine-theme.js
Fixes #263 
Open to suggestions for a better/more reliable way to detect if we're on a mobile device.
=> [PR] Process mobile background images

builder-templates/front-end/h1-header.php, inc/builder.php, inc/builder/core/css/builder.css
Fixes #286, and hooks everything up for saving and displaying column background images on the Header element. @jeremyfelt #reviewmerge?
=> [PR] H1 Header refactor

functions.php, spine/header.php
Fixes #201 @jeremyfelt #reviewmerge?
=> [PR] Spine header link text

includes/theme-navigation.php
Fixes #228 @jeremyfelt #reviewmerge? Also definitely open to discussion!
=> [PR] Add the 'current' class to a pages's parent if it itself is not in the navigation

inc/builder/core/css/builder.css, inc/builder/core/js/views/section.js
Slightly more involved than one would think... @jeremyfelt #reviewmerge?
=> [PR] Make section config modal available when section is closed

style.css
To accompany the changes made via https://github.com/washingtonstateuniversity/WSUWP-Plugin-Embeds/pull/33
=> [PR] Add styles for responsive YouTube embeds

includes/theme-navigation.php
For compatibility with the Spine when 1.4.3 is released.
=> [PR] Change the active menu item class from 'current' to 'active'

includes/theme-navigation.php
Fixes #326 @jeremyfelt #reviewmerge?
=> [PR] Fix Spine navigation error on 404 pages

includes/theme-navigation.php
@jeremyfelt Merging now, please #reviewlater when you get a chance!
=> [PR] Check that the current view is a page before trying to find its parent

functions.php
Per JIRA issue WPTSP-5. @jeremyfelt #reviewmerge?
=> [PR] Add Body Classes meta box

css/editor-opensans.css, css/editor.css, includes/theme-setup.php
Fixes #323 @jeremyfelt #reviewmerge?
=> [PR] Revise editor stylesheet to better match default Spine styles

includes/theme-navigation.php
If this isn't an array, a warning will appear in the PHP logs
=> [PR] Only check for events slug specifics when option is available

functions.php
This should prevent notices from being thrown on archive and other non-single views. @jeremyfelt #reviewmerge?
=> [PR] Check that we're on a page before attempting to retrieve post meta

builder-templates/admin/columns.php, builder-templates/front-end/columns.php, inc/builder.php, style.css
Introduces _Section Title_ and _Section Title Header Level_ inputs to the Section Configuration modal for all Columns sections. @jeremyfelt #reviewmerge?
=> [PR] Section headers

includes/theme-images.php
The previous method was causing some strange issues when trying to
use `wp profile`.
=> [PR] Instantiate Spine_Theme_Images in a smarter way

articles/post.php
=> [PR] Check that a taxonomy exists before looking for it

builder-templates/admin/h1-header.php, builder-templates/front-end/columns.php, builder-templates/front-end/h1-header.php, comments.php, composer.json, functions.php, inc/builder-custom/extras.php, includes/theme-images.php, includes/theme-main-header.php, includes/theme-navigation.php, phpcs.ruleset.xml, spine/footer.php
Adjusts some code styling to match change in tooling.
=> [PR] Update PHPCS to 2.7.x, WPPHPCS to 0.10.0

includes/theme-customizer.php, style.css
- Adds filter 'spine_theme_styles' to spine theme style options.
=> Add filter to theme style select
