single.php
Without `pad-ends`, no padding is on the section, which results
in a display that does not match the rest of our default section
styling.
=> [PR] Add `pad-ends` to section in footer of single views

builder-templates/admin/single.php
The ID used when outputting the column overlay data in the single
section template matched the overlay date used for the section
itself. This caused only the entry for Column configuration to
appear whether configuration was selected for column or section.
Adding a -1 to the ID mimics what we do in our columns layout and
fixes the issue.
Fixes #158
=> [PR] Column overlay in single admin template should have a unique ID

functions.php, includes/customizer/customizer.php
* Adds `spine_get_option_defaults()` for reuse of default options. This allows us to grab a set of defaults to use with our `spine_get_option()` function and in `spine_social_options()`. We can likely use it in Customizer as well at some point in the future.
* Provides defaults for the social spot data.
* Change default Twitter and Youtube URLs to use HTTPS
=> [PR] Ensure defaults are available for social options in the Spine

functions.php
Use the title of the page view and the social options from the Customizer to provide a `spineoptions` object for the Spine as it starts.
Currently requires the `develop` branch of the WSU Spine. Will be added in 1.2.3 shortly.
Fixes #39
=> [PR] Provide sharing text, Twitter text, and Twitter handle to Spine

includes/editor.css
Uses the editor styles from upstream Make as a base. We can change these over time to better match the Spine styles, though these are a decent default.
Does better job of covering image sizes (See #162)
Fixes #163
=> [PR] Improved Editor Styles

functions.php
These classes and the interior span allow for targeting heterogenous
archive listings and overriding default more text using :before or
:after generated content. We already have these tags in place when using a read-more break.
=> Add wrappers for more links when auto truncating

functions.php
If "Skeletal" is chosen as the styling option in the Customizer, we can avoid loading an extra stylesheet entirely. This avoids an unnecessary HTTP request.
In the process, remove all 3 empty CSS files that are not used.
=> [PR] Don't load empty stylesheets by default.

builder-templates/admin/banner.php, builder-templates/admin/columns.php, builder-templates/admin/h1-header.php, builder-templates/css/sections.css, inc/builder.php
This allows a section to be labeled without actually entering a
title that will otherwise appear on the front end as an H1 or H2.
=> [PR] Add a section label configuration to all builder sections

404.php, index.php, page.php, single.php, template-builder.php, templates/halves.php, templates/margin-left.php, templates/margin-right.php, templates/side-left.php, templates/side-right.php, templates/single.php, tribe-events/default-template.php
This matches the parts/headers template that is used directly
inside each `main` opener and allows us to specify a common
content footer throughout a theme.
=> [PR] Add a parts/footers template to all templates closing `main`

includes/theme-navigation.php
Continue to strip all classes from Spine list items and apply current when necessary. Apply current to custom nav menus, but allow those menus to keep any custom classes assigned.
=> [PR] Allow navigation outside of the Spine to retain custom classes

builder-templates/admin/banner.php, builder-templates/admin/columns.php, builder-templates/admin/h1-header.php, builder-templates/css/sections.css, builder-templates/front-end/banner.php, builder-templates/front-end/columns.php, builder-templates/front-end/h1-header.php, inc/builder.php
Section background and mobile background are now available fields in each section configuration.
* If a background is applied to a section, a wrapping `<div>` will be created and assigned the class `section-wrapper-has-background`.
* The background image(s) will be applied via data attributes `data-background-img` and `data-background-mobile-img`.
* At first the only way to access these will be via custom Javascript. In the future, we may have a broader solution available.
=> [PR] Introduce section backgrounds in the builder interface

includes/theme-navigation.php
We've used this previously in the College of Business and WSU Home themes. Needed to highlight the current item in the nav menu when using BU Navigation.
=> [PR] Filter classes in the Spine navigation to add current and dogeared

functions.php
This will aid in using the same stylesheet across multiple sites, especially when a child theme is in use. In the future, we may also have the ability to share custom CSS across sites on a network.
* If on a root site (e.g. mysite.wsu.edu/), the domain class will be `domain-mysite-wsu-edu` and the path class will be `path-none`.
* If on a page on the root site, the domain and path classes will still be `domain-mysite-wsu-edu` and `path-none`.
* If a subsite has been created (e.g. mysite.wsu.edu/site2/), the domain class will be `domain-mysite-wsu-edu` and the path class will be `path-site2`.
* If on a page on the sub site, the domain and path classes will still be `domain-mysite-wsu-edu` and `path-site2`.
=> [PR] Add a site's domain and root path as body classes

functions.php
This will allow very unique sites like Foundation to override the
wsu.edu URL without requiring placement as a campus location.
In the future, this may also allow for interesting possibilities
in Spine usage without the WSU branding. That's less likely.
=> [PR] Provide a filter to override the campus home URL

builder-templates/front-end/banner.php, builder-templates/front-end/columns.php, builder-templates/front-end/h1-header.php
This helps with `-of-type` targetting for a page of sections that have wrappers.
=> [PR] Wrap all sections in a `section-wrapper` class

parts/featured-images.php
It was possible (I think) for an non-existing image to be assigned
as a featured image to a post somehow. This may be due to import
from another WordPress installation. In these cases, an empty
string is returned when we retrieve the featured image source. We
can get around this by checking for a value before outputting any
HTML for the image.
=> [PR] Add a check for empty background and featured images before output

builder-templates/css/sections.css, builder-templates/front-end/columns.php, inc/builder.php
Provides a configuration at the column level for what header to use when displaying a column title. Options are `h2`, `h3`, and `h4`.
=> [PR] Allow for configurable header levels on individual columns

functions.php, js/spine-theme.js
If a background image is assigned to a section, it will now be processed into inline CSS for that section after the page loads.
Fixes #203
=> [PR] Process section background images into actual background images

header.php
This apparently resolves a long standing IE compatibility mode
issue because IE is appearing to ignore the header sent by the
server.
=> [PR] Provide the X-UA-Compatible header in the HTML document

styles/bookmark.css
At this point, the main header is flushed left and no longer needs to be forced to 2000px to aid with spacing.
Fixes #81.
=> [PR] Set main header with to 100% at size-small

functions.php
Previously, an invalid URL would be built on the front end if no
extra Open Sans fonts had been selected.
=> [PR] Only takeover the Open Sans font enqueue when customized

functions.php
The default excerpt functionality in WordPress strips all tags via `wp_trim_words()` as no tags are allowed in excerpts. Because we whitelist a set of tags, we need to account for them being unbalanced after trim. Unbalanced tags create super strange page views... :)
=> [PR] Balance tags when generating a custom excerpt.

functions.php
This appears to have been an accidental change as part of another
commit in 83217097d966cd637bd3
Fixes #243
=> [PR] Set `false` as the default for bleed left in the Spine

builder-templates/css/sections.css, inc/builder/core/css/builder.css
It appears that some default styles were removed or modified in
WordPress 4.4. We can add a few more explicit defaults to resolve.
=> [PR] Adjust visual layout of Make builder after WordPress 4.4

includes/main-header.php
Previously, the `is_singular()` check would not catch the page used for posts and it was impossible to override the sup and sub header values using the provided meta box.
=> [PR] Allow for the override of sup/sub headers on page for posts

includes/customizer/customizer.php
* "light" was only in use on 2 sites in the platform
* "velum" was never properly applied due to a misspelling
Deprecated colors will continue to show in the customizer if it is
currently set for a site. Once the option has been changed to
something else, it will no longer be available.
=> [PR] Deprecate the "light" and "velum" color options in Customizer

spine/header.php, style.css
We've decided that this doesn't need to be a part of all layouts in the primary parent theme.
=> [PR] Remove print tab from Spine header area

style.css
If a floating element exists in a small article, it can overlap
with the article footer unless we clear the float
=> [PR] Clear elements above `.article-footer`

functions.php
Via the `spine_child_min_css` filter, a theme can now specify that a `style.min.css` file is available.
=> [PR] Allow a child theme to provide a minified stylesheet

functions.php
Previously, we allowed the builder module to be included by default
but we did not enable the actual template. This can cause confusion
for those using the theme outside of WSUWP.
=> [PR] Show the builder template as an available option by default

includes/theme-customizer.php
It's helpful to expose the site's title and tagline so that they
can be edited alongside the global header and description. In the
future we'll want to do a better job of describing how these all
interact with each other.
=> [PR] Enable Site Identity customizer section and merge Main Header

functions.php, includes/theme-customizer.php
This was always labeled as the default, but we set gray instead.
=> [PR] Set the default secondary color for Bookmark to Crimson

includes/theme-customizer.php
* Rename "Default (white)" to "White"
* Deprecate lightest, lighter, gray, and darkest options.
* If a site already has one of these deprecated options selected, it will remain until changed.
=> [PR] Adjust Spine color options

builder-templates/front-end/banner.php, style.css
- Removes the `.builder-banner-inner-content *` rule, as it was the most common culprit in breaking custom slideshow styling and would only be of value in cases where a slide has too much content anyway.
- Removes the unnecessary `font-size: 0;` declaration in the `builder-banner-content` class
- Adds prefixes for the Flexbox rules.
- Hides all but first slide on page load*.
- Adjusts positioning of the previous and next controls if the navigation dots are not in use*.
*These will only take effect on existing slideshows after they've been updated.
=> [PR] Banner revisions

inc/builder/core/js/views/section.js
Fixes a bug where collapsed columns within a toggled section would be inaccessible when opened due to the parent section height being fixed, therefore not expanding with it.
=> [PR] Remove inline height after a section has been toggled open

spine/site-navigation.php
Fixes a bug where the Overview link for a section is highlighted even when it's not the current page. @jeremyfelt #reviewmerge?
=> [PR] BU Navigation 'Overview' highlighting

style.css
As bought up in Open Lab, some of WordPress's default widgets (Search and Categories, to name two) have elements which leverage this class, but with no styling in place, those elements are currently visible.
=> [PR] Introduce 'screen-reader-text' class styles

functions.php, includes/theme-customizer.php, js/customizer.js, parts/headers.php
When pages are selected to display as the front page and as the
page for the main posts archive, we should provide a way for those
page titles to display.
This shows options in the customizer for each. These options only
display when static pages are selected. The titles are off by default
to match current behavior and will display when the boxes are checked.
=> [PR] Provide title options for front page and page for posts

functions.php, template-builder.php
* Strip non-allowed tags from excerpts **before** running the excerpt through `the_content` filters so that proper paragraphs are built.
* Allow heading tags - h2, h3, h4, h5 in excerpts.
* Filter local content syndicate items to make sure that `wpautop` is run properly on the full text when output as part of the page builder template.
=> [PR] Correct situational troubles with wpautop and content syndication

includes/theme-navigation.php
* If the page view is for a post, and the BU nav item being output is the front page for posts, mark it as dogeared.
* If this dogeared page has a parent, make sure the chain of "current parent" items is preserved so that the menu is expanded.
=> [PR] Ensure a page for posts is highlighted in nav properly

includes/theme-navigation.php
While viewing events or the calendar page, apply the class to the item with with URL for the calendar page.
While viewing posts, apply the class to the item with the URL that matches the posts page.
=> [PR] Additional logic for applying the 'active' class to BU Nav items

functions.php
Open Sans is no longer used in WordPress 4.6 so we no longer need to font match.
=> [PR] Remove unused Open Sans fonts for WordPress

composer.json, package.json, phpcs.ruleset.xml
There are still some things in the Spine Parent that aren't worth
it to scan for after the fork from upstream Make.
=> [PR] Update PHPCS and adjust default configuration to match

inc/builder/core/css/builder.css
Elements from TinyMCE on previously active sections are playing strangely and will sometimes appear above the overlay. This corrects the immediate issue, though it will be nice to fix the underlying one as well.
=> [PR] Bump the z-index on the builder overlays

functions.php
This allows child themes to provide a version number that can be used when enqueuing their stylesheets automatically in the parent theme.
=> [PR] Provide and use `spine_get_child_version()`

functions.php
The previous was a poort attempt at a wrapper just for the purpose
of better naming. Now that `get_site()` is avaialble in core, we
can get rid of it.
See https://github.com/washingtonstateuniversity/WSUWP-Platform/issues/351
=> Use `get_site()` vs `wsuwp_get_current_site()`

parts/headers.php
This adds support for [Breadcrumb NavXT](https://wordpress.org/plugins/breadcrumb-navxt/), which will be added to the WSU public plugins list shortly.
=> [PR] Add basic support for the breadcrumb-navxt plugin

builder-templates/front-end/columns.php, inc/builder.php
This fixes a bug where a section title added to a single column section would also save as (and overwrite) the column title. Hopefully there are few or no instances of this - it's kind of a silly thing to do anyway - but if there are any, [line 776] (https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/blob/b776c28b6c5c97fac28ab12efef9524bbe6c875b/inc/builder.php#L776) should ensure backward compatibility.
=> [PR] Section title/single column title conflict

articles/post.php
"author" is not a valid `role` value.
=> [PR] Remove invalid "author" role from posts

includes/theme-customizer.php
If crimson is already set as a color option, then we'll continue to present it until it is changed.
This change is being made as part of an accessibility effort.
=> [PR] Remove Crimson as a color option for the Spine

functions.php
This came up in the admin view for WP Event Calendar
=> [PR] Only filter post classes on non-admin views

includes/theme-images.php
If a theme does not account specifically for backround and
thumbnail images, it should have the ability to disable them to
avoid unexpected output.
=> [PR] Provide filters to disable additional featured images

includes/theme-customizer.php
Since these aren't commonly updated, let's not provide defaults
that result in the wrong people being contacted for help.
=> [PR] Remove default contact info customizer option values

functions.php, includes/theme-customizer.php
This ensures that all sites previously configured for "1" or "develop" will use version 1 of the Spine and provides a new option to load version 2, which will be on the develop branch until February 26.
=> [PR] Add support for pre-2.0.0 WSU Spine release

functions.php, templates/gutenberg-beta.php
We should start getting used to Gutenberg as *the* editing tool at some level, even if our primary support for it will be in a new WSU Web Framework theme.
This gets things started and makes it easier to selectively use Gutenberg on pages depending on the template.
The next step will be to start playing with block styles.
=> Build in initial Gutenberg support

includes/theme-setup.php
Save the instance of the Spine Theme Setup class to a variable so that child themes and/or plugins can access it if needed.
=> Store instance of Spine Theme Setup class

parts/share-tools.php
Google plus was shut down back in april and the link currently goes nowhere
=> Removed google plus from spine share options
